### ISSUE TITLE
Supporting number of cases for scraper-hostile sites

### ISSUE THREAD

**Issue by wcedmisten** [mac9416/covid-19-us-state-scraper#1]
You could scrape the html from this [CDC Chart of Reported Cases By State](https://www.cdc.gov/TemplatePackage/contrib/widgets/cdcMaps/build/index.html?chost=www.cdc.gov&cpath=/coronavirus/2019-ncov/cases-updates/cases-in-us.html&csearch=&chash=&ctitle=Cases%20in%20U.S.%20%7C%20CDC&wn=cdcMaps&wf=/TemplatePackage/contrib/widgets/cdcMaps/build/&wid=cdcMaps1&mMode=widget&mPage=&mChannel=&class=mb-3&host=www.cdc.gov&theme=theme-cyan&configUrl=/coronavirus/2019-ncov/map-cases-us.json) to obtain the number of cases for states whose websites are hostile to web scrapers.

This would also allow you to compare the CDC's data with the states' data, which could be interesting.

**Comment by crenshaw-dev** [comment]
Not a bad idea! I'll look at how scrape-able that page is.

There are so many good data sources right now though, I'm beginning to think this repo might best serve as a snapshot of "what the states' sites are saying" rather than definitively "what's the state of the world." Of course, on the other hand, "what the states' sites are saying" may be something no one is interested in.  :-)
